export class OWDictConditions {
    HIDE_TEMPLE_BASEMENT_ENTRIES?: boolean;
    FromGiantsDeep?: boolean;
    LAUNCH_CODES_GIVEN?: boolean;
    HAS_USED_SHIPLOG?: boolean;
    HAS_PLAYER_LOCKED_ON?: boolean;
    HAS_USED_MAP_SHIP?: boolean;
    HAS_PLAYER_LOCKED_ON_MAP?: boolean;
    TM_MOON_CRATER_X1?: boolean;
    HAS_USED_JETPACK?: boolean;
    HAS_USED_MAP_SUIT?: boolean;
    HAS_USED_TRANSLATOR?: boolean;
    HAS_AIMED_TRANSLATOR?: boolean;
    PREFLIGHT_CHECKLIST_UNLOCKED?: boolean;
    HAS_TAKEN_MIDAIR_SNAPSHOT?: boolean;
    HAS_RETRIEVED_PROBE?: boolean;
    TALKED_TO_GABBRO?: boolean;
    GABBRO_MERGE_TRIGGERED?: boolean;
    AskedGabbroForHisShip?: boolean;
    FoundGabbroShip?: boolean;
    SUIT_BOOSTER_FIRED?: boolean;
    HAS_TAKEN_HANDHELD_SNAPSHOT?: boolean;
    HAS_USED_PREFLIGHT_CHECKLIST?: boolean;
    ChertFirstContact?: boolean;
    KILLED_IN_GHOST_MATTER?: boolean;
    MetFeldspar?: boolean;
    EX_ANGLERFISH_NEST?: boolean;
    KNOWS_MEDITATION?: boolean;
    MET_RIEBECK?: boolean;
    MET_SOLANUM?: boolean;
    HAS_SEEN_SUN_EXPLODE?: boolean;
    KILLED_BY_SUPERNOVA_AND_KNOWS_IT?: boolean;
    GAME_OVER_LAST_SAVE?: boolean;
    FoundMapSatellite?: boolean;
    MARK_ON_HUD_TUTORIAL_COMPLETE?: boolean;
    COMPLETED_SHIPLOG_TUTORIAL?: boolean;
    HAS_USED_SLIDE_PROJECTOR?: boolean;
    HAS_ROTATED_PROBE_CAMERA?: boolean
}